config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /es|en/ do
    resources :sensors do
      resources :measures
    end

    devise_for :users, path: :session, controllers: { sessions: 'users/sessions' }

    resources :boards
    resources :locations
    resources :buildings
    resources :users

    post 'sensor_details', to: 'sensors#details', as: :sensors_details
    get 'set_locale', to: 'application#set_locale'
    root 'application#index'
  end

  mount SmartBuildingsManager::API => '/v1'
end

app/views/shared/_breadcrumb.html.erb
<ol class="breadcrumb">
    <li class="">
        <%= content_tag 'a', href: root_path do %>
        <%= content_tag 'i', '', class: "fa fa-home" %>
        <%= content_tag 'span', t('.home') %>
        <% end %>
        <h1>

    </ol>

app/views/shared/_footer.html.erb
<footer role="contentinfo">
  <div class="clearfix">
    <ul class="list-unstyled list-inline pull-left">
      <li>
        <h6>
          &copy; 2016 Patricia Campal</h6>
      </li>
    </ul>
    <button class="pull-right btn btn-link btn-xs hidden-print" id="back-to-top">
      <i class="fa fa-arrow-up"></i>
    </button>
  </div>
</footer>

app/views/shared/_headerbar.html.erb
<div id="headerbar"></div>

<header id="topnav" class="navbar navbar-midnightblue navbar-fixed-top clearfix" role="banner">

    <span id="trigger-sidebar" class="toolbar-trigger toolbar-icon-bg">
        <a data-toggle="tooltips" data-placement="right" title="Toggle Sidebar">
            <span class="icon-bg">
                <i class="fa fa-fw fa-bars"></i>
            </span>
        </a>
    </span>

    <%= link_to t('.sbm'), root_path(), class: 'navbar-brand' %>
    <ul class="nav navbar-nav toolbar pull-right">

        <li class="dropdown toolbar-icon-bg">

            <a href="#" class="dropdown-toggle" data-toggle='dropdown'>
                <span class="icon-bg">
                    <i class="fa fa-fw fa-user"></i>
                </span>
            </a>
            <ul class="dropdown-menu userinfo arrow">
                <li>
                  <%= content_tag 'a', class: "link-locale", href: set_locale_path({ locale: :en }) do %>
                    <%= content_tag 'i', '', class: "fa fa-language" %>
                    <%= content_tag 'span', t('.change_locale_en') %>
                  <% end %>
                </li>

                <li>
                  <%= content_tag 'a', class: "link-locale", href: set_locale_path({ locale: :es }) do %>
                    <%= content_tag 'i', '', class: "fa fa-language" %>
                    <%= content_tag 'span', t('.change_locale_es') %>
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= content_tag 'a', href: user_path(current_user) do %>
                    <span class="pull-left"><%= t('.account') %></span>
                    <i class="pull-right fa fa-user"></i>
                  <% end %>
                </li>
                <li class="divider"></li>
                <li><%= link_to(raw("<span class='pull-left'>#{t('.sign_out')}</span>" +
                                "<i class='pull-right fa fa-sign-out'></i>"), destroy_user_session_path, method: :delete) %>
                </li>
            </ul>
        </li>

    </ul>

</header>

app/views/shared/_messages.html.erb
    <% unless flash.blank? %>
    <div class="alert alert-dismissable alert-info">
    <% flash.keys.each do |key| %>
    <% unless flash[key].blank? %>
    <div class="">
        <i class="fa fa-fw fa-info-circle"></i>
        <%= flash[key] %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    </div>
    <% end %>
    <% end %>
    <% end %>

</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar scroll-content" tabindex="0" style="right: -15px;">
<div class="sidebar">

  <div class="widget stay-on-collapse" id="widget-sidebar">
    <nav role="navigation" class="widget-body">
      <ul class="acc-menu">
        <li class="nav-separator"><%= t(".dashboard") %></li>
        <li class="nav-separator">
        </li>

        <li>
          <a href="javascript:;">
            <i class="fa fa-building"></i>
            <span><%= t('.buildings') %></span>
          </a>
          <ul class="acc-menu">
            <li>
              <%= link_to t('.create_new_building'), new_building_path() %>
            </li>
            <li>
              <%= link_to t('.manage_buildings'), buildings_path() %>
            </li>
          </ul>
        </li>
        <li>
          <a href="javascript:;">
            <i class="fa fa-map-marker"></i>
            <span><%= t('.locations') %></span>
          </a>
          <ul class="acc-menu">
            <li>
              <%= link_to t('.create_new_location'), new_location_path() %>
            </li>
            <li>
              <%= link_to t('.manage_locations'), locations_path() %>
            </li>
          </ul>
        </li>
        <li>
          <a href="javascript:;">
            <i class="fa fa-cogs"></i>
            <span><%= t('.boards') %></span>
          </a>
          <ul class="acc-menu">
            <li>
              <%= link_to t('.create_new_board'), new_board_path() %>
            </li>
            <li>
              <%= link_to t('.manage_boards'), boards_path() %>
            </li>
          </ul>
        </li>
        <li>
          <a href="javascript:;">
            <i class="fa fa-dot-circle-o"></i>
            <span><%= t('.sensors') %></span>
          </a>
          <ul class="acc-menu">
            <li>
              <%= link_to t('.create_new_sensor'), new_sensor_path() %>
            </li>
            <li>
            <%= link_to t('.manage_sensors'), sensors_path() %>
            </li>

          </ul>
        </li>
        <li class="nav-separator">
        </li>
        <% if current_user.is_admin? %>
          <li>
            <a href="javascript:;">
              <i class="fa fa-dot-circle-o"></i>
              <span><%= t('.users') %></span>
            </a>
            <ul class="acc-menu">
              <li>
                <%= link_to t('.create_new_user'), new_user_path() %>
              </li>
              <li>
              <%= link_to t('.manage_users'), users_path() %>
              </li>

            </ul>
          </li>
        <% end %>

      </ul>
     </nav>
  </div>
</div>
</div>