config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /es|en/ do
    resources :sensors do
      resources :measures
    end

    devise_for :users, path: :session, controllers: { sessions: 'users/sessions' }

    resources :boards
    resources :locations
    resources :buildings
    resources :users

    post 'sensor_details', to: 'sensors#details', as: :sensors_details
    get 'set_locale', to: 'application#set_locale'
    root 'application#index'
  end

  mount SmartBuildingsManager::API => '/v1'
end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :locations, dependent: :destroy
  has_and_belongs_to_many :users

  validates :name, presence: true
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :check_permissions, only: [:show, :edit, :update, :destroy]
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = current_user.is_admin? ? Building.all : current_user.buildings
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new

  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: t('.notice4') }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: t('.notice5') }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: t('.notice6') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      # Comprobamos que params[:user_ids] contenga el identificador del current_user.
      # De no contenerlo, se lo añadimos por defecto para asociar el building a su current_user
      if !params[:building][:user_ids].include?(current_user.id)
        params[:building][:user_ids] << current_user.id
      end

      params.require(:building).permit(:name, :description, :address, :postal_code, :phone, user_ids: [])
    end

    def check_permissions
      building = Building.find(params[:id])

      if !current_user.admin? && !current_user.buildings.include?(building)
        redirect_to buildings_path
      end
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<div class="ui-sortable">

	<div class="panel panel-default wijets-full-screen">

		<div class="panel-heading">
			<h2>Formulario edificio</h2>
			<div class="panel-ctrls">
				<span class="button-icon has-bg">
					<i class="fa fa-minus"></i>
				</span>
			</div>
		</div>

		<div class="panel-editbox" data-widget-controls=""></div>

		<div class="panel-body">
			<%= form_for(@building, html: { class: 'form-horizontal row-border' }) do |f| %>
			<% if @building.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@building.errors.count, "error") %>
					prohibited this building from being saved:</h2>

				<ul>
					<% @building.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<% end %>
				</ul>
			</div>
			<% end %>
			<div class="form-group">
				<%= f.label :name, class: 'col-sm-2 control-label' %>
				<div class="col-sm-8">
					<%= f.text_field :name, class: 'form-control tooltips' %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :description, class: 'col-sm-2 control-label' %>
				<div class="col-sm-8">
					<%= f.text_area :description, class: 'form-control tooltips', rows: 10 %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :address, class: 'col-sm-2 control-label' %>
				<div class="col-sm-8">
					<%= f.text_field :address, class: 'form-control tooltips' %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :postal_code, class: 'col-sm-2 control-label' %>
				<div class="col-sm-8">
					<%= f.text_field :postal_code, class: 'form-control tooltips' %>
				</div>
			</div>
			<div class="form-group">
				<%= f.label :phone, class: 'col-sm-2 control-label' %>
				<div class="col-sm-8">
					<%= f.text_field :phone, class: 'form-control tooltips' %>
				</div>
			</div>

			<div class="form-group">
				<%= f.label :user_ids, class: 'col-sm-2 control-label' %>
				<div class="col-sm-8">
					<%= f.select :user_ids, options_from_collection_for_select(User.all, :id, :name, @building.users.map(&:id)),
							{include_blank: t('.select_users')}, { class: 'form-control tooltips', multiple: true, size: 5 } %>
				</div>
			</div>

			<div class="panel-footer">
				<div class="row">
					<div class="col-sm-8 col-sm-offset-2">
						<%= f.submit 'Enviar', class: 'btn-primary btn' %>
						<%= link_to 'Cancelar', buildings_path(), class: 'btn-default btn' %>
					</div>
				</div>
			</div>

			<% end %>
		</div>

	</div>

</div>

app/views/buildings/edit.html.erb
<h1><%= t('.editing_building') %></h1>

<%= render 'form' %>

<%= link_to t('.back'), buildings_path, :class => "btn btn-inverse" %>

app/views/buildings/index.html.erb
<!-- <p id="notice"><%#= notice %></p>

<h2><%#= @message %></h2>
-->

<div class="panel panel-default" id="panel-inline">

    <div class="panel-heading">
        <h2><%= t('.listing_buildings') %></h2>
        <div class="panel-ctrls"></div>
    </div>

    <div class="panel-body panel-no-padding">

        <table class="datatables" id="editable">

            <thead>
                <tr role="row">
                    <th><%= t('.name') %></th>
                    <th><%= t('.description') %></th>
                    <th><%= t('.address') %></th>
                    <th><%= t('.postal_code') %></th>
                    <th><%= t('.phone') %></th>
                    <th><%= t('.Actions') %> </th>
                </tr>
            </thead>

            <tbody>
                <% @buildings.each_with_index do |building, index| %>
                <tr role="row" class="<%= index%2==0 ? 'odd' : 'even' %>">
                    <td><%= building.name %></td>
                    <td><%= building.description %></td>
                    <td><%= building.address %></td>
                    <td><%= building.postal_code %></td>
                    <td><%= building.phone %></td>
                    <td>
                        <%= link_to t('.show'), building, :class => "btn btn-inverse-alt" %>
                        <%= link_to t('.edit'), edit_building_path(building),  :class => "btn btn-warning-alt" %>
                        <%= link_to t('.destroy'), building, method: :delete,  :class => "btn btn-danger-alt", data: { confirm: t('.are_you_sure') } %>
                    </td>
                </tr>
                <% end %>
            </tbody>

        </table>

        <!--end table-->
        <div class="panel-footer"></div>

    </div>

</div>
<%= link_to t('.new_building'), new_building_path, :class=>"btn btn-inverse" %>

app/views/buildings/new.html.erb
<%= render 'form' %>

<%= link_to t('.back'), buildings_path, :class => "btn btn-inverse" %>

app/views/buildings/show.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h2> <%= t('informacion_edificio')%> </h2>
    </div>
    <div class="panel-body panel-no-padding">

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr role="row">
                        <th><%= t('.name') %></th>
                        <th><%= t('.description') %></th>
                        <th><%= t('.address') %></th>
                        <th><%= t('.postal_code') %></th>
                        <th><%= t('.phone') %></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><%= @building.name %></td>
                        <td><%= @building.description %></td>
                        <td><%= @building.address %></td>
                        <td><%= @building.postal_code %></td>
                        <td><%= @building.phone %></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!--end table-->
    </div>
</div>
<%= link_to t('.destroy'), @building, method: :delete, :class => "btn btn-danger-alt" %>

<%= link_to t('.edit'),  edit_building_path(@building), :class => "btn btn-warning-alt" %>

<%= link_to t('.back'), buildings_path, :class => "btn btn-inverse-alt" %>