config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", :locale => /es|en/ do
    resources :sensors do
      resources :measures
    end

    devise_for :users, path: :session, controllers: { sessions: 'users/sessions' }

    resources :boards
    resources :locations
    resources :buildings
    resources :users

    post 'sensor_details', to: 'sensors#details', as: :sensors_details
    get 'set_locale', to: 'application#set_locale'
    root 'application#index'
  end

  mount SmartBuildingsManager::API => '/v1'
end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  belongs_to :user
  belongs_to :board
  has_many :measures, dependent: :destroy

  validates :name, presence: true

  KINDS = [ ['Digital', 0], ['Analog', 1] ]
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :check_permissions, only: [:show, :edit, :update, :destroy]
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = current_user.is_admin? ? Sensor.all : Sensor.includes(:user).where(user: current_user)
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @sensor_measures = @sensor.measures.order('created_at desc').limit(10).map{|m| { time: m.created_at, value: m.value } }
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params.merge!(user: current_user))

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: t('.notice') }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params.merge!(user: current_user))
        format.html { redirect_to @sensor, notice: t('.notice2') }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: t('.notice3') }
      format.json { head :no_content }
    end
  end

  def details
    sensor = Sensor.find(params[:id])
    @sensor_measures = sensor.measures.where('measures.created_at >= ?', eval(params[:period]).day.ago).order('created_at asc').limit(20).map{|m| { time: m.created_at, value: m.value } }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:name, :description, :kind, :board_id)
    end

    def check_permissions
      sensor = Sensor.find(params[:id])

      if !current_user.admin? && !current_user.buildings.map(&:locations).map(&:boards).map(&:sensors).uniq.include?(sensor)
        redirect_to sensors_path
      end
    end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<div class="ui-sortable">

<div class="panel panel-default wijets-full-screen">

	<div class="panel-heading">
		<h2><%= t('.formulario_sensor')%></h2>
		<div class="panel-ctrls">
			<span class="button-icon has-bg">
				<i class="fa fa-minus"></i>
			</span>
		</div>
	</div>

	<div class="panel-editbox" data-widget-controls=""></div>

	<div class="panel-body">
<%= form_for(@sensor, html: { class: 'form-horizontal row-border' }) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="form-group">
		<%= f.label :board_id, class: 'col-sm-2 control-label' %>
		<div class="col-sm-8">
			<%= f.select :board_id, options_from_collection_for_select(current_user.boards.all, :id, :name, @sensor.board_id),
						class: 'form-control tooltips', include_blank: t('.select_a_board') %>
		</div>
	</div>

  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :name, class: 'form-control tooltips' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_area :description, class: 'form-control tooltips', rows: 10 %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :kind, class: 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :kind, class: 'form-control tooltips' %>
    </div>
  </div>

  <div class="panel-footer">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <%= f.submit 'Enviar', class: 'btn-primary btn' %>
        <%= link_to 'Cancelar', sensors_path(), class: 'btn-default btn' %>
      </div>
    </div>
  </div>

<% end %>
</div>

</div>


</div>

app/views/sensors/details.js.erb
console.log('<%= @sensor_measures.to_json %>');
$("#sensor-evolution").html('');
new Morris.Area({
    element: 'sensor-evolution',
    data: <%= raw @sensor_measures.to_json %>,
    xkey: 'time',
    ykeys: ['value'],
    labels: ['Value'],
    pointSize: 2,
    resize: true
});

app/views/sensors/edit.html.erb
<h1><%= t('.editing_sensor') %></h1>

<%= render 'form' %>
<%= link_to t('.back'), sensors_path, :class => "btn btn-inverse" %>

app/views/sensors/index.html.erb
<div class="panel panel-default" id="panel-inline">

    <div class="panel-heading">
        <h2><%= t('.listing_sensors') %></h2>
        <div class="panel-ctrls"></div>
    </div>

    <div class="panel-body panel-no-padding">

        <table class="datatables" id="editable">

            <thead>
                <tr role="row">
                    <th><%= t('.name') %></th>
                    <th><%= t('.description') %></th>
                    <th><%= t('.kind') %></th>
                    <th><%= t('.actions') %>
                    </th>
                </tr>
            </thead>

            <tbody>
                <% @sensors.each do |sensor| %>
                <tr>
                    <td><%= sensor.name %></td>
                    <td><%= sensor.description %></td>
                    <td><%= sensor.kind %></td>
                    <td><i class="fa fa-bar-chart-o"></i> <%= link_to t('.show'), sensor, :class => "btn btn-inverse-alt"  %>
                    <%= link_to t('.edit'), edit_sensor_path(sensor), :class => "btn btn-warning-alt" %>
                    <%= link_to t('.destroy'), sensor, method: :delete, :class => "btn btn-danger-alt", data: { confirm: t('.are_you_sure') } %>
                  </td>
                </tr>
                <% end %>
            </tbody>
        </table>
        <!--end table-->
        <div class="panel-footer"></div>

    </div>

  </div>
  <%= link_to t('.new_sensor'), new_sensor_path, :class=>"btn btn-inverse" %>

app/views/sensors/new.html.erb
<%= render 'form' %>

<%= link_to t('.back'), sensors_path, :class => "btn btn-inverse" %>

app/views/sensors/show.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h2>
            <%= t('.informacion_sensor')%>
        </h2>
    </div>
    <div class="panel-body panel-no-padding">

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr role="row">
                        <th><%= t('.building')%></th>
                        <th><%= t('.location')%></th>
                        <th><%= t('.board')%></th>
                        <th><%= t('.name') %></th>
                        <th><%= t('.description') %></th>
                        <th><%= t('.kind') %></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <%= @sensor.board.location.building.name %>
                        </td>
                        <td>
                            <%= @sensor.board.location.name %>
                        </td>
                        <td>
                            <%= @sensor.board.name %>
                        </td>
                        <td>
                            <%= @sensor.name %>
                        </td>
                        <td>
                            <%= @sensor.description %>
                        </td>
                        <td>
                            <%= @sensor.kind %></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!--end table-->
    </div>
</div>

<!--Grafica -->
<% unless @sensor_measures.blank? %>
<div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <%= t('.sensor_evolution') %>
            <%= form_tag sensors_details_path(), remote: true do %>
              <input type="hidden" name="id" id="id" value="<%= @sensor.id%>" />
              <select class="period" id="period" name="period">
                <option value="">Selecciona un periodo</option>
                <option value="1">Un día</option>
                <option value="7">Una semana</option>
                <option value="30">Un mes</option>
              </select>
          <% end %>
        </div>
        <div class="panel-body">
            <div id="sensor-evolution" style="height: 250px;"></div>
        </div>
    </div>
</div>

<% content_for(:extra_scripts) do %>
<script type="text/javascript">
    $(document).ready(function () {
        new Morris.Area({
            element: 'sensor-evolution',
            data: <%= raw @sensor_measures.to_json %>,
            xkey: 'time',
            ykeys: ['value'],
            labels: ['Value'],
            pointSize: 2,
            resize: true
        });
    });
</script>
<% end %>
<% end %>
<!--PIE-->

<%= link_to t('.destroy'), @sensor, method: :delete, :class => "btn btn-danger-alt" %>

<%= link_to t('.edit'), edit_sensor_path(@sensor), :class => "btn btn-warning-alt" %>

<%= link_to t('.back'), sensors_path, :class => "btn btn-inverse-alt" %>

app/views/sensors/test_pdf.pdf.erb
<h1>
HOLA
</h1>

<div class="">
  <p>
    Que tal estas
  </p>

  <p>
    <% @data_ids.each do |data| %>
      <span><%= data %></span>
    <% end %>
  </p>
  <p>
    <% @data_measures.each do |data| %>
      <span><%= data.map(&:value) %></span>
    <% end %>
  </p>
  <p>
    <% @data_names.each do |data| %>
      <span><%= data %></span>
    <% end %>
  </p>

  <div id="canvas">  </div>
</div>


<script type="text/javascript">
  $(document).ready(function(){

    var ctx = document.getElementById('canvas').getContext('2d');
    var data = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
      datasets: [
        {
          label: "My First dataset",
          fill: false,
          lineTension: 0.1,
          backgroundColor: "rgba(75,192,192,0.4)",
          borderColor: "rgba(75,192,192,1)",
          borderCapStyle: 'butt',
          borderDash: [],
          borderDashOffset: 0.0,
          borderJoinStyle: 'miter',
          pointBorderColor: "rgba(75,192,192,1)",
          pointBackgroundColor: "#fff",
          pointBorderWidth: 1,
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgba(75,192,192,1)",
          pointHoverBorderColor: "rgba(220,220,220,1)",
          pointHoverBorderWidth: 2,
          pointRadius: 1,
          pointHitRadius: 10,
          data: [65, 59, 80, 81, 56, 55, 40],
        }
      ]
    };
    var myLineChart = new Chart(ctx, {
        type: 'line',
        data: data,
        options: {}
    });

  });
</script>